addons:
  firefox: "47.0"
language: node_js
node_js: 
    "6.1"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
- npm install @angular/core
- npm install